version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/docker_pull.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user
