sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.9.0

branches:
  only:
    - master
    - develop
    - testing
    - rails

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install: true

script:
  - docker-compose build
  - docker-compose up -d db
  - sleep 10
  - docker-compose run app rake db:create

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker tag jukeboxapi_app:latest ${ECR_REPO}:${TRAVIS_BRANCH}
  - docker push ${ECR_REPO}:${TRAVIS_BRANCH}
  - sed -i -e "s/DOCKER_IMAGE_NAME/${ECR_REPO}:${TRAVIS_BRANCH}/" Dockerrun.aws.json

deploy:
  - provider: elasticbeanstalk
    app: jukebox-api
    env: rails
    bucket_name: 540co-jukebox-api
    bucket_path: eb/rails
    zip_file: Dockerrun.aws.json
    skip_cleanup: true
    on:
      branch: rails
