version: '2'
services:
  app:
    build: .
    command: ./bin/docker/start
    ports:
      - "9540:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:9.5.4
    expose:
      - "5432"
    volumes_from:
      - db_data
  db_data:
    image: postgres:9.5.4
    command: /bin/true
    volumes:
      - /var/lib/postgresql/data
