version: '2'
services:
  app:
    build: .
    command: node_modules/.bin/nodemon bin/www
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
     - db
    env_file:
     - .env
  db:
    image: postgres
    ports:
     - "5432:5432"
    volumes:
     - /var/lib/postgresql/data
