default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jukebox-api_development

test:
  <<: *default
  database: jukebox-api_test

production:
  <<: *default
  database: <%= ENV['PROD_DB_HOST'] %>
  database: <%= ENV['PROD_DB_PORT'] %>
  database: <%= ENV['PROD_DB_NAME'] %>
  username: <%= ENV['PROD_DB_USER'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
